
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true
    hostname: gaoxiong-eureka
  server:
    enable-self-preservation: false #关闭eureka的自我保护
    eviction-interval-timer-in-ms: 6000 # 每隔6秒剔除一次下线的服务
server:
  port: 9000
spring:
  application:
    name: gaoxiong-eureka