server:
  port: 6003
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/uaa/user # 通过网关访问 获取用户信息
      id: order-service
      prefer-token-info: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka
  instance:
    prefer-ip-address: true